### PR TITLE
Update certificate chain

### PR DESCRIPTION
**Pull request by odedd**

### CODE REVIEW

**Comment by timothystewart6** [comment]
@peter-murray  any chance for a review, merge, and release?

**Comment by timothystewart6** [comment]
Nice work @odedd   I am not sure how to get the 3rd part of the chain but I tested your changes locally against my custom twitch bot and it worked.  Thanks!

**Comment by peter-murray** [comment]
What version are you looking for this fix to end up in? 4.x or 5.x? The `main` branch is not where the 5.x (a.k.a current) versions are.

**Comment by odedd** [comment]
Thank you peter. 
This fix in currently intended for the 4.x branch (that's what I'm using) and I think it's needed as there are other projects still reliant on it, and without it the project breaks. It might also be needed for v5 if it still needs the cert for discovery.meethue.com

**Comment by peter-murray** [comment]
Versions `4.0.11` and `5.0.0-beta.10` have been released with this fix in it. looks likely another release will be required in April once this certificate expires again, the joy of actually enforcing SSL checks 😢

**Comment by timothystewart6** [comment]
Thank you so much!

**Pull request closed without merging**
