### PR TITLE
Enable .rgb() support in .setGroupLightState()

### PR DESCRIPTION
**Pull request by ardouglass**
I don't know if this was left out intentionally, but it works on my bulbs with this fix.

### CODE REVIEW

**Comment by peter-murray** [comment]
Hi,

RGB is not really part of the lights API, it is an addition that I added. The code that you have copied to convert the RGB values does not generate correct colours in extreme ranges, i.e. Black and white. 

I recently rewrote the conversion code, but it needs to apply it to each light as it needs to understand the bounds of the color space. Seeing that a group can include any light bulbs or lamps, and they may not all be the same, it is not trivial to perform this conversion to a group, although entirely doable.

I have been working on releasing the 1.0.0 version of the library that fixes a number of issues with the LightState object, as well as supporting scenes and some other new features. I was aware of what I would need to do around applying RGB colours to a group, but it may not make it into the initial 1.0.0 release and instead be added to a patch or minor release soon after.

Due to the fact the code will not generate the correct colours, I will not apply this pull request, but will open an issue to cater for group RGB colors in the 1.x releases.

**Comment by ardouglass** [comment]
I didn't think about the multiple types of bulbs. That makes sense. What would be the best way to apply color to a group until you add RGB?

**Comment by peter-murray** [comment]
It's a bit of a mess until I release 1.x as the LightState object had a number of bugs around properties and functions overlapping, which caused all kind of issues. Also the deletion of RGB values was a problem, that has since been remediated.

The solution would be to chain a couple of calls, which will be what I do in the final implementation. Effectively you need to get the types of bulbs in the group and put then in sub groups based on type, then perform the RGB transformation for each sub group, and then unfortunately queue multiple calls to each sub group. It is less than optimal, but about the best implementation I can think of for now.

The down and dirty option could be to only allow RGB to be used if the lights are all the same type, and error if that is not the case, or possibly just do one conversion and pass those Love you heaps and miss you lots x y values, as the lights will adjust the values to something within range.

The use of scenes may be an appropriate option too, as in a scene you can set different light settings when you recall the scene. The API currently only has this functionality on the development branch, and I have not fully tested that.

**Comment by ardouglass** [comment]
I like the idea of subgroups and think that could work pretty well. I have groups in my house including "downstairs", "living room", and "living room ceiling fan." I know all of them in the ceiling fan will be the same, but all of them downstairs or in a single room won't necessarily be the same.

**Comment by peter-murray** [comment]
I have just performed a refactoring to support scene definitions and modifications that has resulted in the code for the light state being extracted into a common function.

That should make it relatively easy for me to support RGB on a sub group within a group. I may be able to put something together for the 1.0.x release later this week to cater for your requirement.

**Pull request closed without merging**
